# -*- coding: utf-8 -*-
"""The turbo-geth/silkworm KV application protocol metadata."""

BLOCK_BODIES_LABEL: str = 'b'
BLOCK_HEADERS_LABEL: str = 'h'
BLOCK_RECEIPTS_LABEL: str = 'r'
TRANSACTION_LOOKUP_LABEL: str = 'l'

BLOCK_BODIES_NAME: str = 'Block Bodies'
BLOCK_HEADERS_NAME: str = 'Headers'
BLOCK_RECEIPTS_NAME: str = 'Receipts'
TRANSACTION_LOOKUP_NAME: str = 'Transaction Index'

bucketLabels = [
    BLOCK_BODIES_LABEL,
    BLOCK_HEADERS_LABEL,
    BLOCK_RECEIPTS_LABEL,
    TRANSACTION_LOOKUP_LABEL,
]

bucketDescriptors: [str] = {
    BLOCK_BODIES_LABEL: BLOCK_BODIES_NAME,
    BLOCK_HEADERS_LABEL: BLOCK_HEADERS_NAME,
    BLOCK_RECEIPTS_LABEL: BLOCK_RECEIPTS_NAME,
    TRANSACTION_LOOKUP_LABEL: TRANSACTION_LOOKUP_NAME
}
