version: 2.1

orbs:
  python: circleci/python@1.0.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: pip install --upgrade pip
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run linter
          command: pylint silksnake tests tools
      - run:
          name: Run unit tests
          command: |
            coverage run -m pytest
            coverage report
            coverage html
      - store_artifacts:
          path: htmlcov

workflows:
  main:
    jobs:
      - build-and-test
