version: 2.1

orbs:
  python: circleci/python@1.0.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: "Update submodules"
          command: |
            git submodule sync
            git submodule update --init --recursive
      - run:
          name: Install CMake
          command: |
            sudo apt-get update
            sudo apt-get install -y cmake
      - restore_cache:
          name: "Restore Hunter cache"
          key: &hunter-cache-key hunter-{{ .Environment.CIRCLE_JOB }}-{{checksum "silkworm/cmake/Hunter/config.cmake"}}-{{checksum "silkworm/cmake/Hunter/packages.cmake"}}
      - run:
          name: Run CMake
          working_directory: ~/build/silkworm
          command: cmake ../../project/silkworm -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      - run:
          name: Upgrade pip
          command: pip install --upgrade pip
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Build extensions
          command: python setup.py build
      - save_cache:
          name: "Save Hunter cache"
          key: *hunter-cache-key
          paths:
            - ~/.hunter
      - run:
          name: Run linter
          command: pylint silksnake tests tools
      - run:
          name: Run unit tests
          command: |
            coverage run -m pytest tests/unit
            coverage html
            coverage xml
      - store_artifacts:
          path: htmlcov
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: Build source distribution
          command: python setup.py sdist
      - run:
          name: Build binary distribution
          command: python setup.py bdist_wheel

workflows:
  main:
    jobs:
      - build-and-test
