version: 2.1

orbs:
  python: circleci/python@1.0.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: pytest --version
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
