# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: silksnake/core/remote/proto/kv.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='silksnake/core/remote/proto/kv.proto',
  package='remote',
  syntax='proto3',
  serialized_options=b'\n\020io.turbo-geth.dbB\002KVP\001Z\017./remote;remote',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$silksnake/core/remote/proto/kv.proto\x12\x06remote\"Y\n\x0bSeekRequest\x12\x12\n\nbucketName\x18\x01 \x01(\t\x12\x0f\n\x07seekKey\x18\x02 \x01(\x0c\x12\x0e\n\x06prefix\x18\x03 \x01(\x0c\x12\x15\n\rstartSreaming\x18\x04 \x01(\x08\"\"\n\x04Pair\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c\"%\n\x07PairKey\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05vSize\x18\x02 \x01(\x04\x32\x33\n\x02KV\x12-\n\x04Seek\x12\x13.remote.SeekRequest\x1a\x0c.remote.Pair(\x01\x30\x01\x42)\n\x10io.turbo-geth.dbB\x02KVP\x01Z\x0f./remote;remoteb\x06proto3'
)




_SEEKREQUEST = _descriptor.Descriptor(
  name='SeekRequest',
  full_name='remote.SeekRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bucketName', full_name='remote.SeekRequest.bucketName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='seekKey', full_name='remote.SeekRequest.seekKey', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prefix', full_name='remote.SeekRequest.prefix', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='startSreaming', full_name='remote.SeekRequest.startSreaming', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=137,
)


_PAIR = _descriptor.Descriptor(
  name='Pair',
  full_name='remote.Pair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='remote.Pair.key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='remote.Pair.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=173,
)


_PAIRKEY = _descriptor.Descriptor(
  name='PairKey',
  full_name='remote.PairKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='remote.PairKey.key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vSize', full_name='remote.PairKey.vSize', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=212,
)

DESCRIPTOR.message_types_by_name['SeekRequest'] = _SEEKREQUEST
DESCRIPTOR.message_types_by_name['Pair'] = _PAIR
DESCRIPTOR.message_types_by_name['PairKey'] = _PAIRKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SeekRequest = _reflection.GeneratedProtocolMessageType('SeekRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEEKREQUEST,
  '__module__' : 'silksnake.core.remote.proto.kv_pb2'
  # @@protoc_insertion_point(class_scope:remote.SeekRequest)
  })
_sym_db.RegisterMessage(SeekRequest)

Pair = _reflection.GeneratedProtocolMessageType('Pair', (_message.Message,), {
  'DESCRIPTOR' : _PAIR,
  '__module__' : 'silksnake.core.remote.proto.kv_pb2'
  # @@protoc_insertion_point(class_scope:remote.Pair)
  })
_sym_db.RegisterMessage(Pair)

PairKey = _reflection.GeneratedProtocolMessageType('PairKey', (_message.Message,), {
  'DESCRIPTOR' : _PAIRKEY,
  '__module__' : 'silksnake.core.remote.proto.kv_pb2'
  # @@protoc_insertion_point(class_scope:remote.PairKey)
  })
_sym_db.RegisterMessage(PairKey)


DESCRIPTOR._options = None

_KV = _descriptor.ServiceDescriptor(
  name='KV',
  full_name='remote.KV',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=214,
  serialized_end=265,
  methods=[
  _descriptor.MethodDescriptor(
    name='Seek',
    full_name='remote.KV.Seek',
    index=0,
    containing_service=None,
    input_type=_SEEKREQUEST,
    output_type=_PAIR,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_KV)

DESCRIPTOR.services_by_name['KV'] = _KV

# @@protoc_insertion_point(module_scope)
